# Generated by Django 5.1 on 2026-02-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_car_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('2whiler', '2whiler'), ('4whiler', '4whiler')], default='4-whileer', max_length=20),
        ),
    ]
